baseURL = "http://example.org/"
languageCode = "en-us"
title = "Danntheme Hugo Site"
theme = "danntheme"
googleAnalytics = ""

[params]
  description = "Danntheme Hugo theme template description"

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Articles"
  url = "/blog"


