baseURL = "https://dannb.org/"
languageCode = "en-us"
title = "Dann Berg: thoughts and musings"
theme = "danntheme"
googleAnalytics = ""

[params]
  author = "Dann Berg"
  description = "Dann Berg writes things here. Technology, productivity, startups, and more."

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Articles"
  url = "/blog"

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter"

[[menu.main]]
  name = "Shop"
  url = "https://dannberg.storenvy.com/"

[related]
    threshold = 0
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10
