baseURL = "https://dannb.org/"
languageCode = "en-us"
title = "Dann Berg: blog, newsletter, shop, and more"
theme = "danntheme"
rssLimit = 20
copyright = "2023 Dann Berg. All rights reserved."
googleAnalytics = "UA-60897260-2"

[params]
  author = "Dann Berg"
  description = "Hello, I'm Dann. I'm Director of Community at Vantage (ex-Datadog, ex-FullStory) and writer of blogs and plays on the side. Here be thoughts on finops, technology, productivity, & more."
  images = ["dberg-main-og-image.jpg"]

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Articles"
  url = "/blog"

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter"

[[menu.main]]
  name = "Shop"
  url = "https://dannberg.storenvy.com/"

[related]
    threshold = 0
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10
